version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: vr_db
      POSTGRES_USER: vr_user
      POSTGRES_PASSWORD: vr_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vr_user"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: sh -c "python manage.py migrate && gunicorn mysite.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/static
    environment:
      - DB_NAME=vr_db
      - DB_USER=vr_user
      - DB_PASSWORD=vr_password
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  nginx:
    build: ./vr_site/nginx    # путь к папке, где лежит Dockerfile и nginx.conf
    volumes:
      - static_volume:/static
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: