# Generated by Django 5.2.14 on 2026-05-14 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vr_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vrreview',
            options={'verbose_name': 'Отзыв о VR', 'verbose_name_plural': 'Отзывы о VR'},
        ),
        migrations.AlterField(
            model_name='vrreview',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='vrreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='vrreview',
            name='headset_model',
            field=models.CharField(max_length=200, verbose_name='Модель гарнитуры'),
        ),
        migrations.AlterField(
            model_name='vrreview',
            name='rating',
            field=models.IntegerField(verbose_name='Оценка (1-5)'),
        ),
        migrations.AlterField(
            model_name='vrreview',
            name='username',
            field=models.CharField(max_length=100, verbose_name='Имя пользователя'),
        ),
    ]
