# Generated by Django 5.2.14 on 2026-05-14 01:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vr_site', '0004_remove_vrreview_username_vrreview_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewlike',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vrreview',
            options={'verbose_name': 'Отзыв о VR', 'verbose_name_plural': 'Отзывы о VR'},
        ),
        migrations.AlterUniqueTogether(
            name='reviewlike',
            unique_together={('user', 'review')},
        ),
    ]
